"""
Telegram interface for J.A.R.V.I.S.

Each Telegram user gets their own persistent session (``tg-<user_id>``), so the
memory subsystem gives every user independent history and recall. The bot is a
thin adapter over :class:`~jarvis.core.engine.JarvisEngine`; the conversational
logic lives in the engine, not here.

Features: a localized command menu, an inline language picker (English /
Russian / Uzbek), HTML-formatted UI, and per-user language that the assistant
replies in.

Run it with:

    python -m jarvis.interfaces.telegram_bot     # or: jarvis-bot

``aiogram`` is an optional dependency, imported lazily so the rest of the
package works without it.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from jarvis.config.settings import Settings, get_settings
from jarvis.core.engine import JarvisEngine
from jarvis.i18n import (
    DEFAULT_LOCALE,
    SUPPORTED_LOCALES,
    normalize_locale,
    t,
)
from jarvis.interfaces.user_prefs import UserPreferences
from jarvis.utils.exceptions import ConfigError, JarvisError
from jarvis.utils.logger import get_logger, setup_logging
from jarvis.voice import VoiceService

logger = get_logger(__name__)

# Telegram hard-caps messages at 4096 characters.
_TELEGRAM_MAX = 4096

# Static banner shown on the Tariffs screen (generated by scripts/gen_plan_banner.py).
_PLANS_BANNER = Path(__file__).parent / "assets" / "plans_banner.png"

# Reconnect backoff for the always-on polling loop (seconds).
_POLL_BACKOFF_INITIAL = 3.0
_POLL_BACKOFF_MAX = 300.0

# Labels for the language-picker buttons (shown in each language natively).
_LANGUAGE_LABELS = {
    "en": "🇬🇧 English",
    "ru": "🇷🇺 Русский",
    "uz": "🇺🇿 O'zbek",
}


def session_id_for(user_id: int) -> str:
    """Stable per-user session id."""
    return f"tg-{user_id}"


def split_message(text: str, limit: int = _TELEGRAM_MAX) -> list[str]:
    """Split ``text`` into Telegram-sized chunks on line boundaries."""
    text = text or "…"
    if len(text) <= limit:
        return [text]
    chunks: list[str] = []
    current = ""
    for line in text.split("\n"):
        while len(line) > limit:  # a single very long line
            chunks.append(line[:limit])
            line = line[limit:]
        if len(current) + len(line) + 1 > limit:
            chunks.append(current)
            current = line
        else:
            current = f"{current}\n{line}" if current else line
    if current:
        chunks.append(current)
    return chunks


async def generate_reply(engine: JarvisEngine, user_id: int, text: str,
                        locale: str | None = None, *,
                        match_input_language: bool = False,
                        model_profile: str | None = None,
                        usage=None) -> str:
    """Produce the assistant's reply for a Telegram user (testable core).

    When ``locale`` is given (and ``match_input_language`` is False), the
    assistant is asked to reply in that language. For voice, set
    ``match_input_language=True`` so the reply matches the language the user
    actually spoke, whatever it is. ``model_profile`` picks the user's chosen
    AI. If a ``usage`` store is given, the turn's token count is recorded.
    """
    from jarvis.models.response import Request

    session_id = session_id_for(user_id)
    session = engine.session(session_id)
    if match_input_language:
        session.scratch.pop("language", None)
    elif locale:
        session.scratch["language"] = locale
    if model_profile:
        session.scratch["model_profile"] = model_profile
    elif model_profile == "":  # explicit "Auto" — unpin any earlier model
        session.scratch.pop("model_profile", None)
    try:
        response = await engine.process(Request(text=text, session_id=session_id))
        if usage is not None:
            usage.record(user_id, tokens=response.tokens)
        return response.text
    except JarvisError as exc:
        logger.error("Reply failed for user %s: %s", user_id, exc)
        return t("error", locale, error=str(exc))


def _is_allowed(settings: Settings, user_id: int) -> bool:
    allowlist = settings.telegram_allowlist()
    return not allowlist or user_id in allowlist


def handle_successful_payment(billing, settings: Settings, telegram_user_id: int,
                            charge_id: str, locale: str, *,
                            amount: int = 0, currency: str = "",
                            plan: str | None = None) -> str:
    """Fulfil a paid Telegram invoice and return the reply text (testable core).

    ``plan`` overrides the licence plan name (e.g. a purchased tier "plus" /
    "pro"); when ``None`` the server's default ``billing_plan`` is used.
    """
    days = settings.billing_plan_days or None
    fulfillment = billing.process_payment(
        charge_id,
        telegram_user_id=telegram_user_id,
        plan=plan or settings.billing_plan,
        valid_days=days,
        amount=amount,
        currency=currency,
    )
    if fulfillment is None:  # duplicate delivery of the same charge
        return t("buy_thanks_existing", locale, username="—")
    if fulfillment.created_account:
        return t("buy_thanks_new", locale, username=fulfillment.username,
                password=fulfillment.password)
    return t("buy_thanks_existing", locale, username=fulfillment.username)


def handle_link(service, text: str, telegram_user_id: int, locale: str) -> str:
    """Process ``/link <code>`` and return the reply text (testable core).

    ``service`` is a :class:`~jarvis.licensing.service.LicenseService` or
    ``None`` when accounts are disabled on this server.
    """
    if service is None:
        return t("link_disabled", locale)
    parts = (text or "").split(maxsplit=1)
    code = parts[1].strip() if len(parts) > 1 else ""
    if not code:
        return t("link_usage", locale)
    account = service.confirm_pairing(code, telegram_user_id)
    if account is None:
        return t("link_invalid", locale)
    return t("link_success", locale, username=account.username)


def _resolve_locale(prefs: UserPreferences, user) -> str:
    """User's stored language, else a guess from their Telegram client."""
    stored = prefs.get_language(user.id)
    if stored:
        return stored
    return normalize_locale(getattr(user, "language_code", None))


async def run(settings: Settings | None = None) -> None:
    """Start the Telegram bot (long-polling)."""
    settings = settings or get_settings()
    setup_logging(level=settings.log_level, log_file=settings.log_file)

    if not settings.telegram_bot_token:
        raise ConfigError(
            "TELEGRAM_BOT_TOKEN is not set. Add it to your .env file "
            "(get a token from @BotFather)."
        )

    try:
        from aiogram import Bot, Dispatcher, F
        from aiogram.client.default import DefaultBotProperties
        from aiogram.enums import ChatAction, ParseMode
        from aiogram.filters import Command, CommandStart
        from aiogram.types import (
            BotCommand,
            BufferedInputFile,
            CallbackQuery,
            InlineKeyboardButton,
            InlineKeyboardMarkup,
            Message,
        )
    except ImportError as exc:  # pragma: no cover - optional dependency
        raise ConfigError(
            "The 'aiogram' package is required for the Telegram bot. "
            "Install it with: pip install aiogram"
        ) from exc

    engine = JarvisEngine(settings)
    await engine.start()
    prefs = UserPreferences(settings.memory_db_path)
    voice = VoiceService.from_settings(settings) if settings.voice_enabled else None
    license_service = None
    if settings.auth_enabled:
        from jarvis.licensing import LicenseService
        license_service = LicenseService(
            settings.auth_db_path, token_ttl_hours=settings.auth_token_ttl_hours
        )
    billing = None
    if settings.billing_enabled and license_service is not None:
        from jarvis.billing import BillingService
        billing = BillingService(license_service, settings.auth_db_path)
    from jarvis.interfaces.usage import UsageStore
    usage = UsageStore(settings.memory_db_path)

    from jarvis.billing import PRO, build_plans, resolve_plan
    plans = build_plans(
        free_daily=settings.plan_free_daily,
        plus_daily=settings.plan_plus_daily,
        pro_daily=settings.plan_pro_daily,
        plus_price=settings.plan_plus_price_stars,
        pro_price=settings.plan_pro_price_stars,
    )

    def _user_plan(user_id: int):
        """Resolve a user's tier: admins and unrestricted deployments are Pro;
        otherwise it's the plan on their active licence, else Free."""
        if license_service is None or user_id in settings.telegram_admins():
            return plans[PRO]
        account = license_service.get_account_by_telegram(user_id)
        if account is None:
            return plans["free"]
        import time as _time
        active = next((lic for lic in license_service.list_licenses(account.id)
                    if lic.is_valid(now=_time.time())), None)
        return resolve_plan(active.plan, plans) if active else plans["free"]

    bot = Bot(
        token=settings.telegram_bot_token,
        default=DefaultBotProperties(parse_mode=ParseMode.HTML),
    )
    dp = Dispatcher()

    def _language_keyboard() -> "InlineKeyboardMarkup":
        return InlineKeyboardMarkup(inline_keyboard=[[
            InlineKeyboardButton(text=_LANGUAGE_LABELS[loc], callback_data=f"lang:{loc}")
            for loc in SUPPORTED_LOCALES
        ]])

    def _button(label: str, data: str) -> "InlineKeyboardButton":
        # A "data" that looks like a URL becomes a link button, else a callback.
        if data.startswith("http"):
            return InlineKeyboardButton(text=label, url=data)
        return InlineKeyboardButton(text=label, callback_data=data)

    def _markup(rows) -> "InlineKeyboardMarkup":
        return InlineKeyboardMarkup(inline_keyboard=[
            [_button(label, data) for label, data in row] for row in rows
        ])

    def _main_screen(user_id: int, locale: str):
        from jarvis.interfaces.bot_menu import screen_main
        return screen_main(
            locale,
            is_admin=user_id in settings.telegram_admins(),
            billing_on=billing is not None,
            accounts_on=license_service is not None,
            multi_model=len(engine.llm.list_profiles()) > 1,
            voice_on=voice is not None and voice.stt_available(),
            channel=settings.telegram_channel,
            name=settings.user_name,
            plan=_user_plan(user_id) if billing is not None else None,
            used_today=usage.stats(user_id)["messages_today"],
        )

    async def _is_subscribed(user_id: int) -> bool:
        """True if the user is in the required channel (or none is configured)."""
        channel = settings.telegram_required_channel
        if not channel:
            return True
        try:
            member = await bot.get_chat_member(channel, user_id)
            return member.status not in ("left", "kicked")
        except Exception as exc:  # noqa: BLE001 - treat lookup errors as blocked
            logger.debug("Subscription check failed for %s: %s", user_id, exc)
            return False

    async def _show_gate(message: "Message", locale: str) -> None:
        from jarvis.interfaces.bot_menu import gate_screen
        text, rows = gate_screen(locale, settings.telegram_required_channel)
        await message.answer(text, reply_markup=_markup(rows))

    async def _guard(message: "Message", locale: str) -> bool:
        if _is_allowed(settings, message.from_user.id):
            return True
        await message.answer(t("not_authorized", locale))
        return False

    async def _open_menu(message: "Message", user_id: int, locale: str) -> None:
        text, rows = _main_screen(user_id, locale)
        await message.answer(text, reply_markup=_markup(rows))

    async def _within_limit(message: "Message", user_id: int, locale: str) -> bool:
        """Enforce the daily message allowance. Returns True if the turn is
        allowed; otherwise shows the limit screen and returns False. Only
        applies when billing is on (otherwise everyone is effectively Pro)."""
        if billing is None:
            return True
        plan = _user_plan(user_id)
        used_today = usage.stats(user_id)["messages_today"]
        if plan.within_daily(used_today):
            return True
        from jarvis.interfaces.bot_menu import limit_screen
        text, rows = limit_screen(locale, plan)
        await message.answer(text, reply_markup=_markup(rows))
        return False

    @dp.message(CommandStart())
    async def _start(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if not await _guard(message, locale):
            return
        if not await _is_subscribed(message.from_user.id):
            await _show_gate(message, locale)
            return
        if prefs.get_language(message.from_user.id) is None:
            await message.answer(t("choose_language", locale),
                                reply_markup=_language_keyboard())
        else:
            await _open_menu(message, message.from_user.id, locale)

    def _profile_message(user, locale: str) -> str:
        from jarvis.interfaces.bot_menu import profile_text
        account, verified = None, False
        if license_service is not None:
            acc = license_service.get_account_by_telegram(user.id)
            if acc is not None:
                account, verified = acc.username, acc.telegram_verified
        return profile_text(
            locale, telegram_id=user.id,
            name=user.full_name or user.username or "—",
            language=locale, model=prefs.get_model(user.id) or "",
            account=account, telegram_verified=verified,
            stats=usage.stats(user.id),
        )

    async def _edit(callback: "CallbackQuery", text: str, rows) -> None:
        """Edit the menu message in place (fall back to a new message).

        A photo message (the Tariffs banner) can't be turned back into a text
        message by editing, so it's deleted and replaced with a fresh one.
        """
        msg = callback.message
        if getattr(msg, "photo", None):
            try:
                await msg.delete()
            except Exception:  # noqa: BLE001
                pass
            await msg.answer(text, reply_markup=_markup(rows))
            return
        try:
            await msg.edit_text(text, reply_markup=_markup(rows))
        except Exception:  # noqa: BLE001 - message unchanged / too old
            await msg.answer(text, reply_markup=_markup(rows))

    async def _show_plans(callback: "CallbackQuery", text: str, rows) -> None:
        """Render the Tariffs screen as a banner photo + caption + buttons."""
        msg = callback.message
        if not _PLANS_BANNER.exists():
            await _edit(callback, text, rows)
            return
        from aiogram.types import FSInputFile
        try:
            await msg.delete()
        except Exception:  # noqa: BLE001
            pass
        try:
            await msg.answer_photo(FSInputFile(str(_PLANS_BANNER)),
                                caption=text, reply_markup=_markup(rows))
        except Exception:  # noqa: BLE001 - fall back to plain text
            await msg.answer(text, reply_markup=_markup(rows))

    @dp.callback_query(F.data.startswith("m:"))
    async def _menu_cb(callback: "CallbackQuery") -> None:
        import jarvis.interfaces.bot_menu as bm
        user = callback.from_user
        locale = _resolve_locale(prefs, user)
        parts = callback.data.split(":")
        action = parts[1]
        back = [[(t("menu_back", locale), "m:main")]]

        # The subscription "I subscribed" button needs its own answer (an alert
        # when the user still isn't in the channel), so it can't share the
        # blanket answer() below — Telegram honours only the first answer.
        if action == "checksub":
            if await _is_subscribed(user.id):
                await callback.answer()
                await _edit(callback, *_main_screen(user.id, locale))
            else:
                await callback.answer(t("gate_not_yet", locale), show_alert=True)
            return

        await callback.answer()

        # Admin-only actions: never trust the callback — re-check the caller.
        if action in ("admin", "adminpanel", "adminsales"):
            if user.id not in settings.telegram_admins():
                return
            if action == "admin":
                await _edit(callback, *bm.screen_admin(
                    locale, billing_on=billing is not None))
            elif license_service is None:
                await _edit(callback, t("admin_needs_auth", locale), back)
            else:
                from jarvis.interfaces.admin_panel import (
                    panel_text, sales_report_text)
                body = (panel_text(license_service, billing)
                        if action == "adminpanel"
                        else sales_report_text(license_service, billing))
                await _edit(callback, body, back)
            return

        if action == "main":
            await _edit(callback, *_main_screen(user.id, locale))
        elif action == "voice":
            await _edit(callback, *bm.screen_voice(locale))
        elif action == "settings":
            await _edit(callback, *bm.screen_settings(
                locale, multi_model=len(engine.llm.list_profiles()) > 1))
        elif action == "memory":
            await _edit(callback, *bm.screen_memory(locale))
        elif action == "help":
            await _edit(callback, *bm.screen_help(locale))
        elif action == "link":
            await _edit(callback, *bm.screen_link(locale))
        elif action == "model":
            await _edit(callback, *bm.screen_model(
                locale, engine.llm.list_profiles(), prefs.get_model(user.id) or ""))
        elif action == "language":
            await _edit(callback, *bm.screen_language(locale, locale))
        elif action == "profile":
            await _edit(callback, _profile_message(user, locale),
                        bm.card_rows(locale, "profile"))
        elif action == "usage":
            await _edit(callback, bm.usage_text(locale, usage.stats(user.id)),
                        bm.card_rows(locale, "usage"))
        elif action == "subscription":
            account, lics = None, []
            if license_service is not None:
                acc = license_service.get_account_by_telegram(user.id)
                if acc is not None:
                    account, lics = acc.username, license_service.list_licenses(acc.id)
            await _edit(callback, bm.subscription_text(
                locale, account=account, licenses=lics),
                bm.card_rows(locale, "subscription"))
        elif action == "setmodel":
            choice = parts[2]
            session = engine.session(session_id_for(user.id))
            if choice == "auto":
                prefs.set_model(user.id, "")
                session.scratch.pop("model_profile", None)  # unpin now
            else:
                prefs.set_model(user.id, choice)
                session.scratch["model_profile"] = choice
            await _edit(callback, *bm.screen_settings(
                locale, multi_model=len(engine.llm.list_profiles()) > 1))
        elif action == "setlang":
            new_locale = normalize_locale(parts[2])
            prefs.set_language(user.id, new_locale)
            engine.session(session_id_for(user.id)).scratch["language"] = new_locale
            await _edit(callback, *bm.screen_settings(
                new_locale, multi_model=len(engine.llm.list_profiles()) > 1))
        elif action in ("reset", "forget"):
            # Ask before wiping — these are destructive.
            await _edit(callback, *bm.screen_confirm(locale, action))
        elif action == "reset_do":
            await engine.reset(session_id_for(user.id))
            await _edit(callback, "🧹 " + t("reset_done", locale),
                        [[(t("menu_back", locale), "m:memory")]])
        elif action == "forget_do":
            await engine.forget(session_id_for(user.id))
            await _edit(callback, "🗑 " + t("forget_done", locale),
                        [[(t("menu_back", locale), "m:memory")]])
        elif action == "plans":
            await _show_plans(callback, *bm.screen_plans(
                locale, plans, _user_plan(user.id).name))
        elif action == "buy":
            tier = parts[2] if len(parts) > 2 else None
            await _send_invoice(callback.message, locale, tier)

    async def _send_invoice(message: "Message", locale: str,
                            tier: str | None = None) -> None:
        if billing is None:
            await message.answer(t("buy_disabled", locale))
            return
        # A tiered purchase (plus/pro) carries the tier in the payload and uses
        # that tier's price; a bare purchase falls back to the default plan.
        if tier in plans and tier != "free":
            price = plans[tier].price_stars
            payload = f"jarvis-plan:{tier}"
            title = f"J.A.R.V.I.S. {t(f'plan_{tier}', locale)}"
        else:
            price = settings.billing_price_stars
            payload = "jarvis-license"
            title = t("buy_invoice_title", locale)
        from aiogram.types import LabeledPrice
        await message.bot.send_invoice(
            chat_id=message.chat.id,
            title=title,
            description=t("buy_invoice_desc", locale),
            payload=payload,
            currency="XTR",
            prices=[LabeledPrice(label=title, amount=price)],
        )

    @dp.callback_query(F.data.startswith("lang:"))
    async def _pick_language(callback: "CallbackQuery") -> None:
        locale = normalize_locale(callback.data.split(":", 1)[1])
        prefs.set_language(callback.from_user.id, locale)
        engine.session(session_id_for(callback.from_user.id)).scratch["language"] = locale
        await callback.answer()
        text, rows = _main_screen(callback.from_user.id, locale)
        try:
            await callback.message.edit_text(text, reply_markup=_markup(rows))
        except Exception:  # noqa: BLE001
            await callback.message.answer(text, reply_markup=_markup(rows))

    @dp.pre_checkout_query()
    async def _pre_checkout(query) -> None:
        await query.answer(ok=billing is not None)

    @dp.message(F.successful_payment)
    async def _paid(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if billing is None:
            return
        payment = message.successful_payment
        # A tiered invoice encodes the plan as "jarvis-plan:<tier>".
        plan_override = None
        payload = getattr(payment, "invoice_payload", "") or ""
        if payload.startswith("jarvis-plan:"):
            plan_override = payload.split(":", 1)[1]
        reply = handle_successful_payment(
            billing, settings, message.from_user.id,
            payment.telegram_payment_charge_id, locale,
            amount=payment.total_amount, currency=payment.currency,
            plan=plan_override,
        )
        await message.answer(reply)

    @dp.message(Command("link"))
    async def _link(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if not await _guard(message, locale):
            return
        reply = handle_link(license_service, message.text or "",
                            message.from_user.id, locale)
        await message.answer(reply)

    admins = settings.telegram_admins()

    @dp.message(F.text.startswith("/admin"))
    async def _admin(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if message.from_user.id not in admins:
            await message.answer(t("not_authorized", locale))
            return
        if license_service is None:
            await message.answer(t("admin_needs_auth", locale))
            return
        from jarvis.interfaces.admin_panel import handle_admin_command

        text = message.text or ""
        command = text.split(maxsplit=1)[0].split("@", 1)[0].lower()
        if command == "/admin_post":
            content = text.split(maxsplit=1)[1] if " " in text else ""
            if not content.strip():
                await message.answer(t("admin_post_usage", locale))
                return
            if not settings.telegram_channel:
                await message.answer(t("admin_no_channel", locale))
                return
            await message.bot.send_message(settings.telegram_channel,
                                        content, parse_mode=None)
            await message.answer(
                t("admin_posted", locale, channel=settings.telegram_channel))
            return
        reply = handle_admin_command(license_service, billing, text)
        await message.answer(reply if reply is not None
                            else t("admin_unknown", locale))

    @dp.message(F.text.startswith("/"))
    async def _stray_command(message: "Message") -> None:
        # The bot is fully button-driven: any leftover slash command (from an
        # old client menu or a habit) just re-opens the menu instead of being
        # treated as chat. /start, /link and the /admin* commands are matched
        # by their own handlers above, so they never reach here.
        locale = _resolve_locale(prefs, message.from_user)
        if not await _guard(message, locale):
            return
        if not await _is_subscribed(message.from_user.id):
            await _show_gate(message, locale)
            return
        await _open_menu(message, message.from_user.id, locale)

    @dp.message(F.text)
    async def _chat(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if not await _guard(message, locale):
            return
        if not await _is_subscribed(message.from_user.id):
            await _show_gate(message, locale)
            return
        if not await _within_limit(message, message.from_user.id, locale):
            return
        await message.bot.send_chat_action(message.chat.id, ChatAction.TYPING)
        reply = await generate_reply(
            engine, message.from_user.id, message.text, locale,
            model_profile=prefs.get_model(message.from_user.id),
            usage=usage,
        )
        # LLM output is plain text — disable HTML parsing to avoid entity errors.
        for chunk in split_message(reply):
            await message.answer(chunk, parse_mode=None)

    @dp.message(F.voice)
    async def _voice(message: "Message") -> None:
        locale = _resolve_locale(prefs, message.from_user)
        if not await _guard(message, locale):
            return
        if not await _is_subscribed(message.from_user.id):
            await _show_gate(message, locale)
            return
        if voice is None or not voice.stt_available():
            await message.answer(t("voice_unavailable", locale))
            return
        if not await _within_limit(message, message.from_user.id, locale):
            return

        await message.bot.send_chat_action(message.chat.id, ChatAction.TYPING)
        try:
            file = await message.bot.get_file(message.voice.file_id)
            buffer = await message.bot.download_file(file.file_path)
            transcription = await voice.transcribe(buffer.read())
        except Exception as exc:  # noqa: BLE001 - surface STT failures to the user
            logger.error("Voice transcription failed: %s", exc)
            await message.answer(t("error", locale, error=str(exc)), parse_mode=None)
            return

        if not transcription.text:
            return

        # Reply in whatever language the user actually spoke.
        reply = await generate_reply(
            engine, message.from_user.id, transcription.text, locale,
            match_input_language=True,
            model_profile=prefs.get_model(message.from_user.id),
            usage=usage,
        )
        for chunk in split_message(reply):
            await message.answer(chunk, parse_mode=None)

        if settings.voice_replies and voice.tts_available():
            try:
                audio = await voice.synthesize(reply, transcription.language)
                out = BufferedInputFile(audio, f"reply.{voice.tts_ext}")
                if voice.tts_is_voice_note:
                    await message.answer_voice(out)
                else:
                    await message.answer_audio(out)
            except Exception as exc:  # noqa: BLE001 - text reply already delivered
                logger.warning("Voice synthesis failed: %s", exc)

    async def _set_commands() -> None:
        # Fully button-driven — no user commands at all. Telegram caches the
        # blue "menu" button per client, and older deployments (or a manual
        # @BotFather /setcommands) may have populated it, so clear it
        # explicitly for every public scope, not just the default one.
        from aiogram.types import (
            BotCommandScopeAllGroupChats,
            BotCommandScopeAllPrivateChats,
            BotCommandScopeChat,
            BotCommandScopeDefault,
        )
        for scope in (BotCommandScopeDefault(),
                    BotCommandScopeAllPrivateChats(),
                    BotCommandScopeAllGroupChats()):
            try:
                await bot.delete_my_commands(scope=scope)
            except Exception as exc:  # noqa: BLE001 - non-fatal
                logger.debug("Clearing commands for %s failed: %s", scope, exc)

        # Admins additionally see the owner commands — only in their own chat.
        admin_extra = [
            BotCommand(command="admin", description=t("cmd_admin", DEFAULT_LOCALE)),
            BotCommand(command="admin_sales",
                    description=t("cmd_admin_sales", DEFAULT_LOCALE)),
        ]
        for admin_id in admins:
            try:
                await bot.set_my_commands(
                    admin_extra, scope=BotCommandScopeChat(chat_id=admin_id))
            except Exception as exc:  # noqa: BLE001 - admin hasn't /start-ed yet
                logger.debug("Admin menu for %s skipped: %s", admin_id, exc)

    async def _startup_report() -> None:
        """Log exactly what this process is running, so the deployed state is
        never a guess: version, whether the subscription gate is active, and —
        if it is — whether the bot can actually check membership."""
        from jarvis import __version__
        try:
            me = await bot.get_me()
            who = f"@{me.username}"
        except Exception as exc:  # noqa: BLE001
            who = f"<unknown: {exc}>"
        logger.info("J.A.R.V.I.S. bot %s starting as %s", __version__, who)
        logger.info("Mode: button-only (no user commands). "
                    "billing=%s auth=%s voice=%s",
                    billing is not None, license_service is not None,
                    voice is not None)

        channel = settings.telegram_required_channel
        if not channel:
            logger.warning(
                "SUBSCRIPTION GATE: OFF — TELEGRAM_REQUIRED_CHANNEL is not set, "
                "so everyone can use the bot. Set it in .env (e.g. @your_channel) "
                "and make the bot an admin of that channel to enable the gate.")
            return
        logger.info("SUBSCRIPTION GATE: ON — required channel %s", channel)
        try:
            # If the bot isn't an admin of the channel, get_chat_member for
            # arbitrary users fails and the gate would block everyone — surface
            # that now instead of at first use.
            member = await bot.get_chat_member(channel, (await bot.get_me()).id)
            if member.status not in ("administrator", "creator"):
                logger.warning(
                    "SUBSCRIPTION GATE: the bot is NOT an admin of %s "
                    "(status=%s). Membership checks will fail and block users. "
                    "Add the bot as a channel admin.", channel, member.status)
            else:
                logger.info("SUBSCRIPTION GATE: verified — bot is admin of %s.",
                            channel)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "SUBSCRIPTION GATE: could not verify channel %s (%s). Ensure the "
                "channel exists and the bot is an admin of it.", channel, exc)

    await _set_commands()
    await _startup_report()
    logger.info("Telegram bot starting (long-polling)…")
    try:
        # Keep the sales bot up 24/7: if polling dies (network drop, Telegram
        # hiccup), reconnect with exponential backoff instead of exiting.
        # aiogram already retries transient errors internally; this loop is
        # the belt-and-braces layer on top, and systemd/Docker restart the
        # whole process if even this fails.
        backoff = _POLL_BACKOFF_INITIAL
        while True:
            try:
                await dp.start_polling(bot)
                break  # clean stop (SIGINT/SIGTERM handled by aiogram)
            except asyncio.CancelledError:
                raise
            except Exception as exc:  # noqa: BLE001 - keep the bot alive
                logger.error("Polling crashed: %s — reconnecting in %.0fs",
                            exc, backoff)
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2, _POLL_BACKOFF_MAX)
            else:  # pragma: no cover - defensive
                break
    finally:
        await engine.shutdown()
        if license_service is not None:
            license_service.close()
        usage.close()
        await bot.session.close()


def main() -> int:
    try:
        asyncio.run(run())
        return 0
    except ConfigError as exc:
        logger.error("%s", exc)
        return 1
    except KeyboardInterrupt:  # pragma: no cover
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
